config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'home/index'
  get 'reservations/index'
  get 'reservations/show'
  get 'reservations/new'
  get 'reservations/create'
  get 'reservations/edit'
  get 'reservations/update'
  get 'reservations/destroy'
  get '/account/settings', to: 'users#settings', as: 'account_settings'
  patch '/account/settings', to: 'users#update_settings', as: 'update_account_settings'
  get 'search', to: 'rooms#search'
  get 'users/settings', to: 'users#settings', as: 'edit_user_settings'
  get 'account/edit', to: 'users#edit_account', as: 'edit_account'
  patch 'account/edit', to: 'users#update_account', as: 'update_account'
  get 'profile/edit', to: 'users#edit_profile', as: 'edit_profile'
  patch 'profile/edit', to: 'users#update_profile', as: 'update_profile'
  get 'rooms/:room_id/reservations', to: 'reservations#index', as: 'room_reservations'
  devise_for :users
  resources :rooms, only: [:index, :show, :new, :create]
  resources :reservations
  resources :rooms do
    resources :reservations do
      member do
        get 'confirmation', to: 'reservations#reservation_confirmation'
      end
      collection do
        get 'search'
      end
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  belongs_to :user

  def total_price
    (check_out - check_in).to_i * room.price * guests
  end
  validates :check_in, presence: true
  validates :check_out, presence: true
  validates :guests, presence: true, numericality: { greater_than_or_equal_to: 1 }

  validate :check_in_date_cannot_be_in_the_past
  validate :check_out_date_after_check_in

  def total_price
    return 0 if check_in.nil? || check_out.nil? || guests.nil?
  
    (check_out - check_in).to_i * room.price * guests
  end
  

  private

  def check_in_date_cannot_be_in_the_past
    if check_in.present? && check_in < Date.today
      errors.add(:check_in, "は本日以降の日付を選択してください")
    end
  end

  def check_out_date_after_check_in
    if check_in.present? && check_out.present? && check_out <= check_in
      errors.add(:check_out, "はチェックインより後の日付を選択してください")
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :reservations, dependent: :destroy  
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 1 }
  validates :address, presence: true

  def self.search(area: nil, keyword: nil)
    rooms = Room.all

    if area.present?
      areas = %w(東京 大阪 京都 札幌)
      if areas.include?(area)
        rooms = rooms.where("address LIKE ?", "%#{area}%")
      end
    end

    if keyword.present?
      rooms = rooms.where("name LIKE ? OR description LIKE ?", "%#{keyword}%", "%#{keyword}%")
    end

    rooms
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :rooms, dependent: :destroy
  has_one_attached :avatar
  has_many :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end

    def after_sign_out_path_for(resource_or_scope)
      root_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_reservation, only: [:edit, :update, :destroy]

  def index
    @reservations = current_user.reservations
  end

  def new
    @room = Room.find(params[:room_id])
    @reservation = Reservation.new
  end

  def create
    @room = Room.find(params[:room_id])
    @reservation = @room.reservations.build(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      @reservation.update(confirmed_at: Time.current)
      redirect_to confirmation_room_reservation_path(@room, @reservation)
    else
      render :new
    end
  end

  def reservation_confirmation
    @reservation = Reservation.find(params[:id])
    @room = @reservation.room
    @stay_duration = (@reservation.check_out - @reservation.check_in).to_i
    @total_price = @stay_duration * @reservation.room.price * @reservation.guests
  end


  def edit
  end

  def update
    redirect_to room_reservations_path(@room), notice: '予約が完了しました'
  end

  def show
    @reservation = Reservation.find(params[:id])
    @room = @reservation.room

  end

  def destroy
    @reservation.destroy
    redirect_to room_reservations_path(@room), notice: '予約を削除しました'
  end

  private

  def reservation_params
    params.require(:reservation).permit(:check_in, :check_out, :guests)
  end

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_reservation
    @reservation = @room.reservations.find(params[:id])
  end

  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  def index
    if current_user
      @rooms = current_user.rooms
    else
      @rooms = Room.all
    end
  end

  def show
    @room
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      redirect_to @room, notice: '保存しました'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @room.update(room_params)
      redirect_to @room, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @room.destroy
    redirect_to rooms_url, notice: '削除しました'
  end

  def search
    if params[:area].present?
      @rooms = Room.where("address LIKE ?", "%#{params[:area]}%")
    else
      @rooms = Room.all
    end

    if params[:keyword].present?
      keyword = "%#{params[:keyword]}%"
      @rooms = @rooms.where("name LIKE ? OR description LIKE ?", keyword, keyword)
    end

    render :search
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name, :description, :price, :address, :image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def settings
    @user = current_user
  end

  def update_account
    @user = current_user
    if @user.update_without_password(user_account_params)
      redirect_to account_settings_path, notice: "アカウント情報を更新しました"
    else
      render :edit_account
    end
  end

  def edit_account
    @user = current_user
  end

  def edit_profile
    @user = current_user
  end

  def update_profile
    @user = current_user
    if @user.update(user_profile_params)
      redirect_to account_settings_path, notice: "プロフィールを更新しました"
    else
      render :edit_profile
    end
  end

  private

  def user_account_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

  def user_profile_params
    params.require(:user).permit(:username, :avatar, :bio)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
 <%= form_with url: search_path, method: :get, local: true do |f| %>
  <div class="search-container">
  <div class="search-item">
    <label for="area">エリア検索</label>
    <%= select_tag :area, options_for_select(['', '東京', '大阪', '京都', '札幌']), prompt: 'エリアを選択' %>
  </div>

  <div class="search-item">
    <label for="keyword">フリーワード検索</label>
    <%= text_field_tag :keyword, params[:keyword] %>
  </div>
  <div class="search-item search-button">
      <%= submit_tag '検索', class: 'btn btn-primary' %> <!-- 検索ボタン -->
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <header>
      <nav class="navbar">
        <div class="navbar-left">
          <%= link_to 'とりっぷ', root_path, class: 'navbar-logo' %>
        </div>
        <div class="navbar-right">
          <% if user_signed_in? %>
            <div class="user-info" id="user-info">
              <%= image_tag current_user.avatar, size: "50x50" if current_user.avatar.attached? %>
              <span class="username"><%= current_user.username %></span>
              <button class="dropbtn">▼</button>
              <div class="dropdown-content" id="dropdown-content">
                  <%= link_to '新規の施設登録', new_room_path %>
                  <%= link_to '予約済み一覧', reservations_path %>
                  <%= link_to '登録済み一覧', rooms_path %>
                  <%= link_to 'アカウント設定', edit_user_settings_path %>
                  <%= button_to 'ログアウト', destroy_user_session_path, class: "btn btn-danger w-100", method: :delete %>
                  </div>
              </div>
          <% else %>
            <div class="btn-group">
              <%= link_to '新規登録', new_user_registration_path, class: 'btn btn-primary' %>
              <%= link_to 'ログイン', new_user_session_path, class: 'btn btn-outline-primary ml-2' %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/reservations/create.html.erb
<h1>Reservations#create</h1>
<p>Find me in app/views/reservations/create.html.erb</p>

app/views/reservations/destroy.html.erb
<h1>Reservations#destroy</h1>
<p>Find me in app/views/reservations/destroy.html.erb</p>

app/views/reservations/index.html.erb
<h1 class="text-center my-4">予約済み一覧</h1>

<div style="overflow-x: auto;">
<table class="table table-stried table-hover tablebordered" style="min-width: 1200px;">
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>チェックイン日</th>
      <th>チェックアウト日</th>
      <th>合計金額</th>
      <th>予約確定日時</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
        <td>
          <% if reservation.room.image.attached? %>
            <%= image_tag reservation.room.image, size: "100x100" %>
          <% end %>
        </td>
        <td><%= link_to reservation.room.name, reservation.room %>
        </td>
        <td><%= reservation.room.description %></td>
        <td><%= reservation.check_in.present? ? reservation.check_in.strftime("%Y/%m/%d") : "未定" %></td>
        <td><%= reservation.check_out.present? ? reservation.check_out.strftime("%Y/%m/%d") : "未定" %></td>
        <td><%= number_to_currency(reservation.total_price) %></td>
        <td><%= reservation.confirmed_at.present? ? reservation.confirmed_at.in_time_zone('Asia/Tokyo').strftime("%Y/%m/%d %H:%M") : "未確定" %></td>
        <td> 
          <%= button_to '削除', [reservation.room, reservation], method: :delete, data: { confirm: '本当に削除しますか？' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/reservations/new.html.erb
<div class="container my-4">
  <div class="text-center">
    <div class="room-image mb-4">
      <% if @room.image.attached? %>
        <%= image_tag @room.image, size: "300x300", alt: "Room Image", class: "img-thumbnail" %> <!-- 施設の画像を表示 -->
      <% else %>
        <p>画像がありません</p>
      <% end %>
    </div>

    <h2><%= @room.name %></h2>
    <p>料金: <%= number_to_currency(@room.price) %> /日</p>

    <% if @reservation.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <ul>
          <% @reservation.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: [@room, @reservation], local: true, method: :post) do |form| %>
      <div class="form-group mb-3">
        <%= form.label :check_in, 'チェックイン日' %>
        <%= form.date_field :check_in, class: 'form-control' %>
      </div>
      <div class="form-group mb-3">
        <%= form.label :check_out, 'チェックアウト日' %>
        <%= form.date_field :check_out, class: 'form-control' %>
      </div>
      <div class="form-group mb-3">
        <%= form.label :guests, '人数' %>
        <%= form.number_field :guests, class: 'form-control', min: 1 %>
      </div>
      <div class="d-flex justify-content-between mt-4">
        <%= form.submit '予約する', class: 'btn btn-primary' %>
        <%= link_to '戻る', rooms_path, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/reservations/reservation_confirmation.html.erb
<div class="container my-4">
<h2 class="text-center mb-4">予約内容の確認</h2>

<div class="card">
    <div class="card-body">
      <p>チェックイン: <%= @reservation.check_in.strftime("%Y/%m/%d") %></p>
      <p>チェックアウト: <%= @reservation.check_out.strftime("%Y/%m/%d") %></p>
      <p>日数: <%= @stay_duration %> 日</p>
      <p>人数: <%= @reservation.guests %> 人</p>
      <p>お支払い金額: <%= number_to_currency(@total_price) %></p>
      <p>上記内容で正しければ「確定」ボタンを押してください。</p>
    </div>
  </div>

<%= form_with model: [@room, @reservation], local: true do |form| %>
  <div class="text-center mt-4">
    <%= form.submit '確定', class: 'btn btn-primary me-2' %>
    <%= link_to '戻る', new_room_reservation_path(@room), class: 'btn btn-secondary' %>
  </div>
<% end %>

</div>

app/views/reservations/show.html.erb
<h1>Reservations#show</h1>
<p>Find me in app/views/reservations/show.html.erb</p>

app/views/reservations/update.html.erb
<h1>Reservations#update</h1>
<p>Find me in app/views/reservations/update.html.erb</p>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/destroy.html.erb
<h1>Rooms#destroy</h1>
<p>Find me in app/views/rooms/destroy.html.erb</p>

app/views/rooms/edit.html.erb
<h2 class="text-center my-4">施設情報の編集</h2>

<% if @room.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="col-md-6 mx-auto">
  <%= form_with model: @room, local: true do |form| %>
    <div class="form-group mb-3">
      <%= form.label :name, "施設名", class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :description, "施設詳細", class: "form-label" %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :price, "料金", class: "form-label" %>
      <%= form.number_field :price, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :address, "住所", class: "form-label" %>
      <%= form.text_field :address, class: "form-control" %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :image, "画像", class: "form-label" %>
      <%= form.file_field :image, class: "form-control" %>
      <% if @room.image.attached? %>
        <p class="mt-2">現在の画像:</p>
        <%= image_tag @room.image, size: "100x100", class: "img-thumbnail" %>
      <% end %>
    </div>

    <div class="text-center">
      <%= form.submit '更新', class: 'btn btn-primary' %>
      <%= link_to 'キャンセル', rooms_path, class: 'btn btn-secondary ml-2' %>
    </div>
  <% end %>
</div>

app/views/rooms/index.html.erb
<h1 class="text-center my-4">登録済み一覧</h1>

<div style="overflow-x: auto;">
<table class="table table-stried table-hover tablebordered" style="min-width: 1200px;">
  <thead>
    <tr>
      <th>画像</th>
      <th>施設名</th>
      <th>紹介文</th>
      <th>宿泊料金</th>
      <th>作成日</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td>
          <% if room.image.attached? %>
            <%= image_tag room.image, size: "100x100" %>
          <% end %>
        </td>
        <td><%= link_to room.name, new_room_reservation_path(room) %></td>
        <td><%= room.description %></td>
        <td><%= room.price %> 円/日</td>
        <td><%= room.created_at.strftime("%Y/%m/%d") %></td>
        <td>
        <%= link_to '編集', edit_room_path(room), class: 'btn btn-warning' %>
        </td>
        <%= form_with(url: room_path(room), method: :delete, local: true, style: "display:inline") do %>
        <td>
          <%= button_tag '削除', type: 'submit', class: 'btn btn-danger', data: { confirm: '本当に削除しますか？' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/rooms/new.html.erb
<h2 class="text-center my-4">新規登録</h2>

<% if @room.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row justify-content-center">
  <div class="col-md-8">
    <%= form_with model: @room, local: true, html: { class: 'form-group' } do |form| %>
      <div class="form-group mb-3">
        <%= form.label :name, "施設名", class: 'form-label' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :description, "施設詳細", class: 'form-label' %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :price, "料金(1日あたり)", class: 'form-label' %>
        <%= form.number_field :price, class: 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :address, "住所", class: 'form-label' %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :image, "画像", class: 'form-label' %>
        <%= form.file_field :image, class: 'form-control' %>
      </div>

      <div class="d-flex justify-content-between mt-4">
        <%= form.submit '登録', class: 'btn btn-primary' %>
        <%= link_to 'キャンセル', :back, class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/search.html.erb
<h1>検索結果</h1>

<p>合計件数: <%= @rooms.count %> 件</p>

<table>
  <thead>
    <tr>
      <th>施設名</th>
      <th>住所</th>
      <th>施設詳細</th>
      <th>宿泊料金（/日）</th>
    </tr>
  </thead>
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= link_to room.name, room_path(room) %></td>
        <td><%= room.address %></td>
        <td><%= room.description %></td>
        <td><%= number_to_currency(room.price) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rooms/show.html.erb
<h1 class="text-center my-4"><%= @room.name %></h1>

<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead class="thead-dark">
      <tr>
        <th scope="col">画像</th>
        <th scope="col">施設名</th>
        <th scope="col">紹介文</th>
        <th scope="col">宿泊料金</th>
        <th scope="col">住所</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>
          <% if @room.image.attached? %>
            <%= image_tag @room.image, size: "100x100", class: "img-thumbnail" %>
          <% else %>
            <span class="text-muted">画像なし</span>
          <% end %>
        </td>
        <td><%= @room.name %></td>
        <td><%= @room.description %></td>
        <td><%= @room.price %> 円 /日</td>
        <td><%= @room.address %></td>
      </tr>
    </tbody>
  </table>
</div>

<div class="text-center mt-4">
  <%= link_to '戻る', :back, class: 'btn btn-secondary' %>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>

app/views/users/edit_account.html.erb
<h1 class="text-center my-4">アカウント情報の編集</h1>

<%= form_with model: @user, url: update_account_path, local: true do |form| %>
  <div class="container">
    <div class="mb-4">
      <%= form.label :email, "メールアドレス", class: "form-label" %>
      <%= form.email_field :email, class: "form-control" %>
    </div>
    
    <div class="mb-4">
      <%= form.label :password, "新しいパスワード", class: "form-label" %>
      <%= form.password_field :password, class: "form-control" %>
    </div>
    
    <div class="mb-4">
      <%= form.label :password_confirmation, "パスワード確認", class: "form-label" %>
      <%= form.password_field :password_confirmation, class: "form-control" %>
    </div>

    <div class="d-flex justify-content-between">
      <%= form.submit "保存", class: "btn btn-primary" %>
      <%= link_to 'キャンセル', account_settings_path, class: 'btn btn-secondary' %> <!-- キャンセルボタン -->
    </div>
  </div>
<% end %>

app/views/users/edit_profile.html.erb
<h1 class="text-center my-4">プロフィールの編集</h1>

<%= form_with model: @user, url: update_profile_path, local: true do |form| %>
  <div class="container">
    <div class="mb-4">
      <%= form.label :avatar, "アイコン画像", class: "form-label" %>
      <%= form.file_field :avatar, class: "form-control" %>
      <% if @user.avatar.attached? %>
        <div class="mt-2">
          <%= image_tag @user.avatar, size: "100x100", class: "img-thumbnail" %>
        </div>
      <% else %>
        <p class="text-danger">アバター画像が設定されていません。</p>
      <% end %>
    </div>

    <div class="mb-4">
      <%= form.label :username, "名前", class: "form-label" %>
      <%= form.text_field :username, class: "form-control" %>
    </div>

    <div class="mb-4">
      <%= form.label :bio, "自己紹介", class: "form-label" %>
      <%= form.text_area :bio, class: "form-control" %>
    </div>

    <div class="d-flex justify-content-between">
      <%= form.submit "保存", class: "btn btn-primary" %>
      <%= link_to 'キャンセル', account_settings_path, class: 'btn btn-secondary' %> <!-- キャンセルボタン -->
    </div>
  </div>
<% end %>

app/views/users/settings.html.erb
<%= form_with model: @user, url: update_account_settings_path, local: true do |form| %>
  <div class="container">
    <div class="row my-4">
      <div class="col-md-6">
        <h2>アカウント情報</h2>
        
        <div class="mb-3">
          <%= form.label :email, "メールアドレス", class: "form-label" %>
          <p class="form-control-plaintext"><%= @user.email %></p>
        </div>
        
        <div class="mb-3">
          <%= form.label :password, "パスワード", class: "form-label" %>
          <p class="form-control-plaintext">*********</p>
        </div>

        <div class="mb-3">
          <%= link_to "アカウント情報の編集", edit_account_path, class: "btn btn-secondary" %>
        </div>
      </div>

      <div class="col-md-6">
        <h2>プロフィール</h2>
        
        <div class="mb-3">
          <%= form.label :avatar, "アイコン画像", class: "form-label" %>
          <% if @user.avatar.attached? %>
            <div class="mb-3">
              <%= image_tag @user.avatar, size: "100x100", class: "img-thumbnail" %>
            </div>
          <% else %>
            <p class="text-danger">アバター画像が設定されていません。</p>
          <% end %>
        </div>

        <div class="mb-3">
          <%= form.label :username, "名前", class: "form-label" %>
          <p class="form-control-plaintext"><%= @user.username %></p>
        </div>

        <div class="mb-3">
          <%= form.label :bio, "自己紹介", class: "form-label" %>
          <p class="form-control-plaintext"><%= @user.bio %></p>
        </div>

        <div class="mb-3">
          <%= link_to "プロフィールの編集", edit_profile_path, class: "btn btn-secondary" %>
        </div>
      </div>
    </div>
  </div>
<% end %>